<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeTwoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeTwoRepository extends EntityRepository
{
}
